apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    project: expense
    module: backend 
spec:
  containers:
  - name: nginx
    image: nginx
  nodeSelector:
    hardware: gpu
  tolerations:
  - key: "hardware"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"
