apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    purpose: affinity
spec:
  containers:
  # docker run -d --name nginx nginx
  - name: nginx
    image: nginx:stable-perl
---
apiVersion: v1
kind: Pod-2
metadata:
  name: nginx-podss
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: name
            operator: In
            values:
            - pod-1
        topologyKey: topology.kubernetes.io/zone
  containers:
  - name: nginx
    image: nginx

